<?php

namespace richweber\gender\helpers;

use Yii;

/**
 * Class SupportedCountries
 * @package richweber\gender\helpers
 */
class SupportedCountries
{
    /**
     * Check supported country
     *
     * @param string $country Country code
     *
     * @return boolean
     */
    public static function isSupportedCountry($country)
    {
        if (array_key_exists($country, self::getSupportedCountries())) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Get supported countries
     *
     * @return array
     */
    public static function getSupportedCountries()
    {
        return [
            'AD' => Yii::t('gender', 'Andorra'),
            'AE' => Yii::t('gender', 'United Arab Emirates'),
            'AF' => Yii::t('gender', 'Afghanistan'),
            'AL' => Yii::t('gender', 'Albania'),
            'AM' => Yii::t('gender', 'Armenia'),
            'AO' => Yii::t('gender', 'Angola'),
            'AR' => Yii::t('gender', 'Argentina'),
            'AT' => Yii::t('gender', 'Austria'),
            'AU' => Yii::t('gender', 'Australia'),
            'AZ' => Yii::t('gender', 'Azerbaijan'),
            'BA' => Yii::t('gender', 'Bosnia and Herzegovina'),
            'BB' => Yii::t('gender', 'Barbados'),
            'BD' => Yii::t('gender', 'Bangladesh'),
            'BE' => Yii::t('gender', 'Belgium'),
            'BF' => Yii::t('gender', 'Burkina Faso'),
            'BG' => Yii::t('gender', 'Bulgaria'),
            'BH' => Yii::t('gender', 'Bahrain'),
            'BI' => Yii::t('gender', 'Burundi'),
            'BJ' => Yii::t('gender', 'Benin'),
            'BN' => Yii::t('gender', 'Brunei'),
            'BO' => Yii::t('gender', 'Bolivia'),
            'BR' => Yii::t('gender', 'Brazil'),
            'BS' => Yii::t('gender', 'Bahamas'),
            'BW' => Yii::t('gender', 'Botswana'),
            'BY' => Yii::t('gender', 'Belarus'),
            'CA' => Yii::t('gender', 'Canada'),
            'CD' => Yii::t('gender', 'Congo - Kinshasa'),
            'CG' => Yii::t('gender', 'Congo - Brazzaville'),
            'CH' => Yii::t('gender', 'Switzerland'),
            'CI' => Yii::t('gender', 'Côte d’Ivoire'),
            'CL' => Yii::t('gender', 'Chile'),
            'CM' => Yii::t('gender', 'Cameroon'),
            'CN' => Yii::t('gender', 'China'),
            'CO' => Yii::t('gender', 'Colombia'),
            'CR' => Yii::t('gender', 'Costa Rica'),
            'CU' => Yii::t('gender', 'Cuba'),
            'CV' => Yii::t('gender', 'Cape Verde'),
            'CY' => Yii::t('gender', 'Cyprus'),
            'CZ' => Yii::t('gender', 'Czech Republic'),
            'DE' => Yii::t('gender', 'Germany'),
            'DJ' => Yii::t('gender', 'Djibouti'),
            'DK' => Yii::t('gender', 'Denmark'),
            'DO' => Yii::t('gender', 'Dominican Republic'),
            'DZ' => Yii::t('gender', 'Algeria'),
            'EC' => Yii::t('gender', 'Ecuador'),
            'EE' => Yii::t('gender', 'Estonia'),
            'EG' => Yii::t('gender', 'Egypt'),
            'ES' => Yii::t('gender', 'Spain'),
            'ET' => Yii::t('gender', 'Ethiopia'),
            'FI' => Yii::t('gender', 'Finland'),
            'FJ' => Yii::t('gender', 'Fiji'),
            'FR' => Yii::t('gender', 'France'),
            'GA' => Yii::t('gender', 'Gabon'),
            'GB' => Yii::t('gender', 'United Kingdom'),
            'GE' => Yii::t('gender', 'Georgia'),
            'GF' => Yii::t('gender', 'French Guiana'),
            'GH' => Yii::t('gender', 'Ghana'),
            'GI' => Yii::t('gender', 'Gibraltar'),
            'GM' => Yii::t('gender', 'Gambia'),
            'GN' => Yii::t('gender', 'Guinea'),
            'GP' => Yii::t('gender', 'Guadeloupe'),
            'GQ' => Yii::t('gender', 'Equatorial Guinea'),
            'GR' => Yii::t('gender', 'Greece'),
            'GT' => Yii::t('gender', 'Guatemala'),
            'GY' => Yii::t('gender', 'Guyana'),
            'HK' => Yii::t('gender', 'Hong Kong SAR China'),
            'HN' => Yii::t('gender', 'Honduras'),
            'HR' => Yii::t('gender', 'Croatia'),
            'HT' => Yii::t('gender', 'Haiti'),
            'HU' => Yii::t('gender', 'Hungary'),
            'ID' => Yii::t('gender', 'Indonesia'),
            'IE' => Yii::t('gender', 'Ireland'),
            'IL' => Yii::t('gender', 'Israel'),
            'IN' => Yii::t('gender', 'India'),
            'IQ' => Yii::t('gender', 'Iraq'),
            'IR' => Yii::t('gender', 'Iran'),
            'IS' => Yii::t('gender', 'Iceland'),
            'IT' => Yii::t('gender', 'Italy'),
            'JE' => Yii::t('gender', 'Jersey'),
            'JM' => Yii::t('gender', 'Jamaica'),
            'JO' => Yii::t('gender', 'Jordan'),
            'JP' => Yii::t('gender', 'Japan'),
            'KE' => Yii::t('gender', 'Kenya'),
            'KG' => Yii::t('gender', 'Kyrgyzstan'),
            'KH' => Yii::t('gender', 'Cambodia'),
            'KM' => Yii::t('gender', 'Comoros'),
            'KR' => Yii::t('gender', 'South Korea'),
            'KW' => Yii::t('gender', 'Kuwait'),
            'KZ' => Yii::t('gender', 'Kazakhstan'),
            'LA' => Yii::t('gender', 'Laos'),
            'LB' => Yii::t('gender', 'Lebanon'),
            'LK' => Yii::t('gender', 'Sri Lanka'),
            'LR' => Yii::t('gender', 'Liberia'),
            'LS' => Yii::t('gender', 'Lesotho'),
            'LT' => Yii::t('gender', 'Lithuania'),
            'LU' => Yii::t('gender', 'Luxembourg'),
            'LV' => Yii::t('gender', 'Latvia'),
            'LY' => Yii::t('gender', 'Libya'),
            'MA' => Yii::t('gender', 'Morocco'),
            'MC' => Yii::t('gender', 'Monaco'),
            'MD' => Yii::t('gender', 'Moldova'),
            'ME' => Yii::t('gender', 'Montenegro'),
            'MG' => Yii::t('gender', 'Madagascar'),
            'MK' => Yii::t('gender', 'Macedonia'),
            'ML' => Yii::t('gender', 'Mali'),
            'MM' => Yii::t('gender', 'Myanmar [Burma]'),
            'MN' => Yii::t('gender', 'Mongolia'),
            'MQ' => Yii::t('gender', 'Martinique'),
            'MR' => Yii::t('gender', 'Mauritania'),
            'MT' => Yii::t('gender', 'Malta'),
            'MU' => Yii::t('gender', 'Mauritius'),
            'MV' => Yii::t('gender', 'Maldives'),
            'MW' => Yii::t('gender', 'Malawi'),
            'MX' => Yii::t('gender', 'Mexico'),
            'MY' => Yii::t('gender', 'Malaysia'),
            'MZ' => Yii::t('gender', 'Mozambique'),
            'NA' => Yii::t('gender', 'Namibia'),
            'NC' => Yii::t('gender', 'New Caledonia'),
            'NE' => Yii::t('gender', 'Niger'),
            'NG' => Yii::t('gender', 'Nigeria'),
            'NI' => Yii::t('gender', 'Nicaragua'),
            'NL' => Yii::t('gender', 'Netherlands'),
            'NO' => Yii::t('gender', 'Norway'),
            'NP' => Yii::t('gender', 'Nepal'),
            'NZ' => Yii::t('gender', 'New Zealand'),
            'OM' => Yii::t('gender', 'Oman'),
            'PA' => Yii::t('gender', 'Panama'),
            'PE' => Yii::t('gender', 'Peru'),
            'PF' => Yii::t('gender', 'French Polynesia'),
            'PG' => Yii::t('gender', 'Papua New Guinea'),
            'PH' => Yii::t('gender', 'Philippines'),
            'PK' => Yii::t('gender', 'Pakistan'),
            'PL' => Yii::t('gender', 'Poland'),
            'PR' => Yii::t('gender', 'Puerto Rico'),
            'PS' => Yii::t('gender', 'Palestinian Territories'),
            'PT' => Yii::t('gender', 'Portugal'),
            'PY' => Yii::t('gender', 'Paraguay'),
            'QA' => Yii::t('gender', 'Qatar'),
            'RE' => Yii::t('gender', 'Réunion'),
            'RO' => Yii::t('gender', 'Romania'),
            'RS' => Yii::t('gender', 'Serbia'),
            'RU' => Yii::t('gender', 'Russia'),
            'RW' => Yii::t('gender', 'Rwanda'),
            'SA' => Yii::t('gender', 'Saudi Arabia'),
            'SC' => Yii::t('gender', 'Seychelles'),
            'SD' => Yii::t('gender', 'Sudan'),
            'SE' => Yii::t('gender', 'Sweden'),
            'SG' => Yii::t('gender', 'Singapore'),
            'SH' => Yii::t('gender', 'Saint Helena'),
            'SI' => Yii::t('gender', 'Slovenia'),
            'SK' => Yii::t('gender', 'Slovakia'),
            'SL' => Yii::t('gender', 'Sierra Leone'),
            'SN' => Yii::t('gender', 'Senegal'),
            'SO' => Yii::t('gender', 'Somalia'),
            'SV' => Yii::t('gender', 'El Salvador'),
            'SY' => Yii::t('gender', 'Syria'),
            'SZ' => Yii::t('gender', 'Swaziland'),
            'TD' => Yii::t('gender', 'Chad'),
            'TG' => Yii::t('gender', 'Togo'),
            'TH' => Yii::t('gender', 'Thailand'),
            'TJ' => Yii::t('gender', 'Tajikistan'),
            'TM' => Yii::t('gender', 'Turkmenistan'),
            'TN' => Yii::t('gender', 'Tunisia'),
            'TR' => Yii::t('gender', 'Turkey'),
            'TT' => Yii::t('gender', 'Trinidad and Tobago'),
            'TW' => Yii::t('gender', 'Taiwan'),
            'TZ' => Yii::t('gender', 'Tanzania'),
            'UA' => Yii::t('gender', 'Ukraine'),
            'UG' => Yii::t('gender', 'Uganda'),
            'US' => Yii::t('gender', 'United States'),
            'UY' => Yii::t('gender', 'Uruguay'),
            'UZ' => Yii::t('gender', 'Uzbekistan'),
            'VE' => Yii::t('gender', 'Venezuela'),
            'VN' => Yii::t('gender', 'Vietnam'),
            'YE' => Yii::t('gender', 'Yemen'),
            'ZA' => Yii::t('gender', 'South Africa'),
            'ZM' => Yii::t('gender', 'Zambia'),
            'ZW' => Yii::t('gender', 'Zimbabwe'),
        ];
    }
}
